# Variables are case sensitive.
[Fst, TStart]          : 30.
[Fst, TMax]            : 130.
[Fst, OutFileFmt]      : 2
[Fst, CompElast]       : 1
[Fst, CompSub]         : 0

[AeroDyn15, TwrPotent] : 0
[AeroDyn15, TwrShadow] : False
[AeroDyn15, TwrAero]   : False

[ElastoDyn, PtfmSgDOF] : False
[ElastoDyn, PtfmSwDOF] : False
[ElastoDyn, PtfmHvDOF] : False
[ElastoDyn, PtfmRDOF]  : False
[ElastoDyn, PtfmPDOF]  : False
[ElastoDyn, PtfmYDOF]  : False

# Flags
[ElastoDyn, SumPrint]   : False
[AeroDyn15, SumPrint]   : False